### ISSUE TITLE
fatal: not a git repository: .git

### ISSUE THREAD

**Issue by August-wind** [ingeniarius-ltd/aquatic_simulator#1]
I get an error when executing the code "git checkout bfb40cb" and others about "git checkout", I don't know what to do. Hope that answers my question, any help is greatly appreciated.

**Comment by aaraujo11** [comment]
Hello @August-wind, after you clone the repo you need, to enter in the folder and only then perform the git checkout, for instance, after
`git clone https://github.com/uuvsimulator/uuv_simulator.git` just do **cd uuv_simulator** and only then, 
`checkout bfb40cb`

**Comment by August-wind** [comment]
Thank you most sincerely. My folders have changed.
